config/routes.rb
Rails.application.routes.draw do
  resources :songs
  resources :users, only: [:new,:create,:show]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :categories
  end 
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
end

app/models/song.rb
class Song < ActiveRecord::Base
  validates_presence_of :title, :artist
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, presence: true,
                       uniqueness: true

  enum role: %w(default admin)
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  def index
    @categories = Category.all
  end

  def new
  end

  def create
    @category = Category.new(category_params)
      if @category.save
       session[:most_recent_category_id] = @category.id
       flash[:notice] = "You have created a new song category"
       redirect_to admin_categories_path
     else
       flash.now[:wrong] = "Invalid Category"
       render :new
     end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :most_recent_song, :current_user
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    def most_recent_song
        @song ||= Song.find(session[:most_recent_song_id]) if session[:most_recent_song_id]
    end

    def current_user
      @user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def current_admin?
      current_user && current_user.admin?
    end
 end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:error] = "Invalid Credentials Try Again"
      render :new
    end
  end

  def destroy
    session.clear
    flash.now[:logout] = "Goodbye!"
    render :new
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update]
  def index
    @songs = Song.all
  end

  def show
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      session[:most_recent_song_id] = @song.id
      flash[:notice] = "bruh you created a yung new new song called #{@song.title} by #{@song.artist}"
      redirect_to songs_path
    else
      flash.now[:errors] = "BRUH!"
      render :new
    end
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to @song
    else
      flash.now[:errors] = @song.errors.full_messages.join(",")
      render :edit
    end
  end

  def destroy
    song = Song.find(params[:id])
    song.destroy
    redirect_to songs_path
  end

  private
  def set_song
    @song = Song.find(params[:id])
  end
  def song_params
    params.require(:song).permit(:title, :artist)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else

    end
  end

  def show
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/admin/categories/index.html.erb
<h1>All Categories</h1>

app/views/admin/categories/new.html.erb
<%= form_for(Category.new, url:"/admin/categories") do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.submit "Create New Category" %>
<%end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyJams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p>
    <% if @song != nil %>
      <strong>Newest song:</strong> <%= most_recent_song.title %>
      <% else  %>
      <%end %>
  </p>

    <%flash.each do |type, msg| %>
      <%=content_tag :div, msg, class: "flash_#{type}" %>
    <% end %>

    <% if current_user %>
      Welcome, <%= current_user.username %>
      <%= link_to 'Logout', logout_path, method: :delete %>
    <% else %>
      <%= link_to 'Login', login_path %>
    <% end %>

<%= yield %>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :artist %>
  <%= f.text_field :artist %>  <br>
  <%= f.submit %>
<%end %>

app/views/songs/edit.html.erb
<h1> YER DUMB BUD </h1>
<%= render partial: 'form' %>

app/views/songs/index.html.erb
<h1> All Songs</h1>
<% @songs.each do |song|%>
  <li>
    <%= link_to song.title, song %>
    <%= link_to "Edit" ,edit_song_path(song) %>
    <%= link_to "Delete", song_path(song),method: :delete %>
  </li>
  <% end %>
<%= link_to 'New Song', new_song_path %> <br>
<%= link_to 'Create New User', new_user_path %> 

app/views/songs/new.html.erb
<h1> BRUH GIVE ME DAT YUNG NEW NEW DAT GOOD GOOD<strong></strong></h1>
<%= render partial: 'form' %>

app/views/songs/show.html.erb
<h1><%=@song.title%></h1>
<p> <%=@song.artist%>

app/views/users/new.html.erb
<h1> Create a New user </h1>

<%= form_for(User.new) do |f|%>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <%= f.submit 'Create Account' %>

<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= current_user.username %>.</h1>